[profile.default]
src = "src"
out = "out"
test = "test"
libs = ["dependencies"]
via_ir = true
gas_limit = 9223372036854775807

fs_permissions = [{ access = "read", path = "./"}]

# See more wagmi options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

solc_version = "0.8.26"

[dependencies]
"@openzeppelin-contracts" = { version = "5.0.2" }
forge-std = { version = "1.8.2" }


[rpc_endpoints]
amoy = "${AMOY_RPC_URL}"

[etherscan]
amoy = { key = "${AMOY_ETHERSCAN_API_KEY}", chain = "amoy", url = "https://api-amoy.polygonscan.com/api?" }
